/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas.dzikrifauziramdhani;

/**
 *
 * @author ADVAN
 */
public class mainFrames extends javax.swing.JFrame {

    /**
     * Creates new form mainFrames
     */
    public mainFrames() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        inputProdukMenu = new javax.swing.JMenuItem();
        pemesananMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        tampilDataMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        deskPane.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout deskPaneLayout = new javax.swing.GroupLayout(deskPane);
        deskPane.setLayout(deskPaneLayout);
        deskPaneLayout.setHorizontalGroup(
            deskPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );
        deskPaneLayout.setVerticalGroup(
            deskPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );

        jMenu1.setText("Transaksi");

        inputProdukMenu.setText("Input Produk");
        inputProdukMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputProdukMenuActionPerformed(evt);
            }
        });
        jMenu1.add(inputProdukMenu);

        pemesananMenu.setText("Pemesanan");
        pemesananMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemesananMenuActionPerformed(evt);
            }
        });
        jMenu1.add(pemesananMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Data");

        tampilDataMenu.setText("Tampil Data");
        tampilDataMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilDataMenuActionPerformed(evt);
            }
        });
        jMenu2.add(tampilDataMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tampilDataMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilDataMenuActionPerformed
         tampilData tampilData = new tampilData();
        tampilData.setVisible(true);
        deskPane.add(tampilData);
    }//GEN-LAST:event_tampilDataMenuActionPerformed

    private void inputProdukMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputProdukMenuActionPerformed
        inputProduk inputProduk = new inputProduk();
        inputProduk.setVisible(true);
        deskPane.add(inputProduk);
    }//GEN-LAST:event_inputProdukMenuActionPerformed

    private void pemesananMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemesananMenuActionPerformed
         pemesanan pemesanan = new pemesanan();
        pemesanan.setVisible(true);
        deskPane.add(pemesanan);
    }//GEN-LAST:event_pemesananMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane deskPane;
    private javax.swing.JMenuItem inputProdukMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem pemesananMenu;
    private javax.swing.JMenuItem tampilDataMenu;
    // End of variables declaration//GEN-END:variables
}
